// const express = require('express');
// const router = express.Router();
// const Receipt = require('../models/Receipt');
// const Request = require('../models/request');
// const { cloudinary } = require('../config/cloudinary');

// // Generate receipt
// router.post('/generate', async (req, res) => {
//   try {
//     console.log("📄 Receipt data received:", req.body);
    
//     const { signature, ...receiptData } = req.body;
//     let signatureUrl = signature; // Already uploaded?

//     // Validate required fields
//     if (!receiptData.owner || !receiptData.ownerId || !receiptData.requestId || !receiptData.receipt_no) {
//       console.log("❌ Missing required fields:", receiptData);
//       return res.status(400).json({ success: false, message: "Missing required fields" });
//     }

//     if (signature && signature.startsWith("data:image")) {
//        const uploadRes = await cloudinary.uploader.upload(signature, {
//         folder: "Roomify/signatures",
//       });
//       signatureUrl = uploadRes.secure_url;
//     }

//     // Explicitly create an object to ensure it's "flat"
//     const newReceipt = new Receipt({
//       owner: receiptData.owner,
//       ownerId: receiptData.ownerId,
//       requestId: receiptData.requestId,
//       receipt_no: receiptData.receipt_no, // THIS IS THE KEY
//       date: receiptData.date,
//       tenant_name: receiptData.tenant_name,
//       property_address: receiptData.property_address,
//       rent_amount: receiptData.rent_amount || 0,
//       charges: receiptData.charges || { 
//         water: 0, 
//         electricity: 0, 
//         wifi: 0,
//         cleaning: 0,
//         food: 0,
//         tax: 0 
//       },
//       total_amount: receiptData.total_amount || 0,
//       signature: signatureUrl
//     });

//     const saved = await newReceipt.save();
    
//     // Update request status to approved
//     await Request.findByIdAndUpdate(receiptData.requestId, { 
//       status: 'approved',
//       ownerDeleted: true 
//     });

//     res.status(201).json({ success: true, receipt: saved });

//   } catch (err) {
//     console.error("❌ Error:", err.message);
//     res.status(400).json({ success: false, message: err.message });
//   }
// });

// // Get receipt by request ID
// router.get('/request/:requestId', async (req, res) => {
//   try {
//     // We find the receipt linked to this specific booking request
//     const receipt = await Receipt.findOne({ requestId: req.params.requestId })
//       .populate('ownerId', 'name email');

//     if (!receipt) {
//       return res.status(404).json({ message: "Receipt not generated by owner yet." });
//     }

//     res.status(200).json(receipt);
//   } catch (err) {
//     console.error("Error fetching receipt:", err.message);
//     res.status(500).json({ message: "Internal Server Error" });
//   }
// });

// // Get receipt by ID
// router.get('/:id', async (req, res) => {
//   try {
//     const receipt = await Receipt.findById(req.params.id)
//       .populate('ownerId', 'name email')
//       .populate('requestId', 'pgId userId');

//     if (!receipt) {
//       return res.status(404).json({ message: "Receipt not found." });
//     }

//     res.status(200).json(receipt);
//   } catch (err) {
//     console.error("Error fetching receipt:", err.message);
//     res.status(500).json({ message: "Internal Server Error" });
//   }
// });

// module.exports = router;
const express = require('express');
const router = express.Router();
const Receipt = require('../models/Receipt');
const Request = require('../models/request');
const multer = require("multer");
const { storage } = require("../config/cloudinary"); // Path to your cloudinary config
const { protect, ownerOnly } = require("../Middleware/auth"); // Path to your auth middleware

// Initialize Multer with your Cloudinary Storage
const upload = multer({ storage });

// ==========================================================================
// 1. GENERATE RECEIPT (POST)
// ==========================================================================
// We use upload.single("signature") to handle the file upload to Cloudinary
router.post('/generate', protect, ownerOnly, upload.single("signature"), async (req, res) => {
  try {
    // 1. Multer puts text fields in req.body and the Cloudinary URL in req.file
    console.log("📄 Form fields received:", req.body);
    
    const signatureUrl = req.file ? req.file.path : ""; 

    // 2. Parse 'charges' (Sent as JSON string from Frontend FormData)
    let charges = { water: 0, electricity: 0, tax: 0 };
    if (req.body.charges) {
      charges = typeof req.body.charges === 'string' 
        ? JSON.parse(req.body.charges) 
        : req.body.charges;
    }

    // 3. Validate Critical Fields
    if (!req.body.requestId || !req.body.receipt_no || !req.body.tenant_name) {
      return res.status(400).json({ success: false, message: "Missing required receipt fields" });
    }

    // 4. Create and Save Receipt
    const newReceipt = new Receipt({
      owner: req.body.owner,
      ownerId: req.user._id, // Set from protect middleware
      requestId: req.body.requestId,
      receipt_no: req.body.receipt_no,
      date: req.body.date || Date.now(),
      tenant_name: req.body.tenant_name,
      property_address: req.body.property_address,
      rent_amount: Number(req.body.rent_amount) || 0,
      charges: charges,
      total_amount: Number(req.body.total_amount) || 0,
      signature: signatureUrl // ✅ This is now the Cloudinary URL
    });

    const saved = await newReceipt.save();
    
    // 5. Update Request status
    // Note: We keep status as 'approved'. If you want it hidden from 'Pending', 
    // ensure your dashboard filter checks for status: 'pending'.
    await Request.findByIdAndUpdate(req.body.requestId, { 
      status: 'approved'
    });

    res.status(201).json({ success: true, receipt: saved });

  } catch (err) {
    console.error("❌ Receipt Generation Error:", err.message);
    res.status(400).json({ success: false, message: err.message });
  }
});

// ==========================================================================
// 2. FETCHING ROUTES (GET)
// ==========================================================================

// Get receipt by request ID (Used by ReceiptView.jsx)
router.get('/request/:requestId', protect, async (req, res) => {
  try {
    const receipt = await Receipt.findOne({ requestId: req.params.requestId })
      .populate('ownerId', 'name email');

    if (!receipt) {
      return res.status(404).json({ message: "Receipt not generated yet." });
    }

    res.status(200).json(receipt);
  } catch (err) {
    res.status(500).json({ message: "Internal Server Error" });
  }
});

// Get specific receipt by its own ID
router.get('/:id', protect, async (req, res) => {
  try {
    const receipt = await Receipt.findById(req.params.id)
      .populate('ownerId', 'name email');

    if (!receipt) {
      return res.status(404).json({ message: "Receipt not found." });
    }

    res.status(200).json(receipt);
  } catch (err) {
    res.status(500).json({ message: "Internal Server Error" });
  }
});

module.exports = router;